'use-strict';

/**
 * The PersonDTO class
 */
class PersonDTO {

    /**
     * The constructor of PersonDTO
     * 
     * @param {Integer} personId The id of the newly created person. 
     *                           This will be automatically generated by the database.
     * @param {String} name The name of the person
     * @param {String} surname The surname of the person
     * @param {String} pnr The personal number of the person
     * @param {String} email The email of the person
     * @param {String} password The password of the password
     * @param {String} roleId The role of the person
     * @param {String} username the username of the person
     */
    constructor(personId, name, surname, pnr, email, password, roleId = 2, username) {
        this.personId = personId;
        this.name = name;
        this.surname = surname;
        this.pnr = pnr;
        this.email = email;
        this.password = password;
        this.role_id = roleId;
        this.username = username;
    }
}

module.exports = PersonDTO;